### ISSUE TITLE
Have random word draw from list

### ISSUE THREAD

**Issue by joshnylander** [elinorn/hangman#9]
Add a new drop down to the 1 Player start which selects from easy, medium, and hard.  Pressing the Random Word button then executes a call to random to select a word from the selected list.  Use list lenght as max.
.
// Returns a random number between min (inclusive) and max (exclusive)
function getRandomArbitrary(min, max) {
  return Math.random() \* (max - min) + min;
}

**Comment by elinorn** [comment]
Elinor and I fixed this.  There are now three short lists that the single player can select from.
